SPACESHIP_SUDO_SHOW=true

SPACESHIP_TIME_SHOW=true
SPACESHIP_TIME_12HR=true
SPACESHIP_TIME_FORMAT='%D{%a %H:%M}'

SPACESHIP_BATTERY_SHOW=always
SPACESHIP_EXIT_CODE_SHOW=false
SPACESHIP_DIR_TRUNC_REPO=false

SPACESHIP_VI_MODE_INSERT="[INSERT] "
SPACESHIP_VI_MODE_NORMAL="[NORMAL] "

SPACESHIP_PROMPT_PREFIXES_SHOW=false
SPACESHIP_PROMPT_SUFFIXES_SHOW=false

SPACESHIP_PROMPT_SEPARATE_LINE=true
SPACESHIP_PROMPT_ADD_NEWLINE=true

SPACESHIP_EXEC_TIME_ELAPSED=60 #sec
SPACESHIP_BATTERY_THRESHOLD=50 #%

SPACESHIP_RPROMPT_ORDER=(
  vi_mode
  #time
  battery
)

# Remove from left prompt
spaceship remove time
spaceship remove battery
