#! /bin/bash
# alias: brew adopt
#
# This is a Homebrew alias script. It'll be called when the
# user type `brew adopt`. Any remaining argument is
# passed to this script. You can retrieve those with $*, or
# the first one only with $1. Please keep your script on
# one line.

# TODO Replace the line below with your script
brew install --cask --adopt $*

