#!/usr/bin/env zsh

TARGET="/Users/$USER/Downloads"
SOURCE="/Users/$USER/Library/Mobile Documents/com~apple~CloudDocs/Downloads"

if [ "$(uname)" != "Darwin" ]; then
  echo "Skipping Downloads pointing on non-MacOS platform"
  exit 0
fi

if [ ! -h "$TARGET" ]; then
  if [ -d "$TARGET" ]; then
    sudo mv "$TARGET" "/Users/$USER/.dotfiles/backup/$TARGET"
    sudo rm -rf "$TARGET"
  fi

  ln -s "$SOURCE" "$TARGET"
  chmod -h 700 "$TARGET" 
fi
