#!/usr/bin/env zsh

curl -L "https://iterm2.com/shell_integration/zsh" -o "$HOME/.iterm2_shell_integration.zsh"

git clone "git@github.com:mbadolato/iTerm2-Color-Schemes.git" "$HOME/.iterm2/iTerm2-Color-Schemes"

