#!/usr/bin/env zsh

if [ "$(uname)" != "Darwin" ]; then
  echo "Skipping Downloads pointing on non-MacOS platform"
  exit 0
fi

# Copy services from iCloud
SOURCE="$HOME/Library/Mobile Documents/com~apple~CloudDocs/Services"
TARGET="$HOME/Library/Services"

if [ -d "$TARGET" ]; then
  DIR=$(pwd)
  cd $SOURCE
  cp * "$TARGET"
  cd $DIR
fi

# SSH
SOURCE="$HOME/Library/Mobile Documents/com~apple~CloudDocs/.ssh"
TARGET="$HOME/.ssh"

if [ ! -h "$TARGET" ]; then
  if [ -d "$TARGET" ]; then
    sudo mv "$TARGET" "$HOME/.dotfiles/backup/$TARGET"
    sudo rm -rf "$TARGET"
  fi

  ln -s "$SOURCE" "$TARGET"
  chmod 700 "$TARGET"
  chmod 600 id_rsa* &> /dev/null
  ssh-add &> /dev/null
fi

